server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456
      maximum-pool-size: 50
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

image-config:
  imgLocation: D://image
  urlPrefix: http://localhost:8080/image/
  annoImgLocation: D://image
  #开启标注模式，开启后，图片检索功能便会关闭
  startAnno: false
  colorMomentsMaxValue: 40
  orbMinValue: 0.5

#logging:
#  level:
#    com.example.imageRetrieval.mapper: DEBUG